name: lprint
base: core22
version: "1.3.2"
summary: A Label Printer Application
description: |
   LPrint implements printing for a variety of common label and receipt printers
   connected via network or USB.  Features include:

   - A single executable handles spooling, status, and server functionality.
   - Multiple printer support.
   - Each printer implements an IPP Everywhere™ print service and is compatible
     with the driverless printing support in iOS, macOS, and Linux clients.
   - Each printer can support options such as label modes, tear-off offsets,
     media tracking, media top offset, print darkness, resolution, roll
     selection, and speed.
   - Each printer can print "raw", Apple/PWG Raster, and/or PNG files.

   For more information, see the file "DOCUMENTATION.md", the man pages in the
   "man" directory, and/or the LPrint project page at
   "https://www.msweet.org/lprint".

grade: stable
confinement: strict
icon: static-resources/lprint.png

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
    lprint:
        command: bin/lprint
        plugs: [avahi-control, home, network, network-bind, network-manager, raw-usb]

    lprint-server:
        command: bin/lprint-server
        daemon: simple
        plugs: [avahi-control, home, network, network-bind, network-manager, raw-usb]

hooks:
    configure:
        plugs: [avahi-control, home, network, network-bind, network-manager, raw-usb]

parts:
    libcups3:
        plugin: autotools
        autotools-configure-parameters: [--disable-shared]
        source-type: git
        source: https://github.com/OpenPrinting/libcups.git
        build-packages: [libavahi-client-dev, libssl-dev, zlib1g-dev]
        stage-packages: [libavahi-client3]

    pappl:
        plugin: autotools
        autotools-configure-parameters: [--disable-shared,--enable-libjpeg,--enable-libpng,--enable-libusb]
        source-type: git
        source: https://github.com/michaelrsweet/pappl.git
        source-branch: v1.4.x
        after: [libcups3]
        build-packages: [libavahi-client-dev, libjpeg8-dev, libpam-dev, libpng-dev, libssl-dev, libusb-1.0-0-dev, zlib1g-dev]
        stage-packages: [libavahi-client3, libjpeg8, libpng16-16, libusb-1.0-0]

    hooks:
        plugin: dump
        source: snap/hooks
        organize:
          configure: snap/hooks/

    scripts:
        plugin: dump
        source: snap/local
        organize:
          lprint-server: bin/

    lprint:
        plugin: autotools
        autotools-configure-parameters: [--prefix=/]
        source: .
        after: [libcups3, pappl, hooks, scripts]
